version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - node1
      - node2
      - node3

  node1:
    build: ./backend
    environment:
      - NODE_ID=node1
      - IS_LEADER=true
    ports:
      - "3501:3500"

  node2:
    build: ./backend
    environment:
      - NODE_ID=node2
      - IS_LEADER=false
    ports:
      - "3502:3500"

  node3:
    build: ./backend
    environment:
      - NODE_ID=node3
      - IS_LEADER=false
    ports:
      - "3503:3500"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Host:Container Port Mapping für das Frontend
